// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from helloworld.djinni

#import <Foundation/Foundation.h>
@class RNCPP_HelloWorld;


@interface RNCPP_HelloWorld : NSObject

+ (nullable RNCPP_HelloWorld *)create;

- (nonnull NSString *)getHelloWorld;

@end
